repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.2.2
    hooks:
      - id: pylint
        additional_dependencies:
          - "openai~=1.30"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
